server:
  port:
    8989

spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://order-service-svc
          predicates:
            - Path=/orders/**
        - id: payment-service
          uri: lb://payment-service-svc
          predicates:
            - Path=/payment/**
eureka:
  enabled: false

order-service-svc:
  ribbon:
    listOfServers: order-service.default.svc.cluster.local:9092

payment-service-svc:
  ribbon:
    listOfServers: payment-service.default.svc.cluster.local:9091

#eureka:
#  instance:
#    preferIpAddress: true
#    hostname: eureka-0
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    serviceUrl:
#      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka