
server:
  port: 8761

eureka:
  instance:
    hostname: eureka-0
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://eureka-0.eureka:8761/eureka}