apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-app
  labels:
    app: order-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service-app
  template:
    metadata:
      labels:
        app: order-service-app
    spec:
      containers:
        - name: order-service-app
          image: riddhijani/order-service:2.0
          imagePullPolicy: Always
          ports:
            - containerPort: 9092
          env:
            - name: DB_HOST
              value: mysql.sql.svc.cluster.local
            - name: DB_NAME
              value: microservice
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: password

---

kind: Service
apiVersion: v1
metadata:
  name: order-service-svc
spec:
  selector:
    app: order-service-app
  ports:
    - port: 9092
      targetPort: 9092
